"""
模型导出代码生成器

根据训练结果生成可复用的 Python 脚本和 Markdown 摘要。
"""

import inspect
import textwrap
from typing import Any, Dict, List, Optional

from core.modeling_engine import ModelLibrary, TaskType, CVResult


def generate_model_export(
    model_key: str,
    task_type: TaskType,
    model_spec: Any,
    params: Dict[str, Any],
    preprocessing_info: Dict[str, Any],
    encoding_report: Optional[List[Dict]] = None,
    feature_selection_report: Optional[List[Dict]] = None,
    cv_result: Optional[CVResult] = None,
    df_sample: Optional[Dict] = None,
) -> Dict[str, str]:
    """
    生成模型摘要和可复用代码。

    Returns:
        {'summary': str, 'code': str, 'model_name': str}
    """
    summary = _generate_summary(
        model_key, task_type, model_spec, params,
        preprocessing_info, cv_result
    )
    code = _generate_code(
        model_key, task_type, model_spec, params,
        preprocessing_info, encoding_report,
        feature_selection_report, df_sample
    )
    return {
        'summary': summary,
        'code': code,
        'model_name': model_spec.name if model_spec else model_key,
    }


def _generate_summary(
    model_key: str,
    task_type: TaskType,
    model_spec: Any,
    params: Dict[str, Any],
    preprocessing_info: Dict[str, Any],
    cv_result: Optional[CVResult] = None,
) -> str:
    """生成 Markdown 摘要。"""
    model_name = model_spec.name if model_spec else model_key
    task_label = task_type.value
    primary_metric = _get_primary_metric(task_type)

    lines = [
        f"# 📋 模型摘要：{model_name}",
        "",
        "## 基本信息",
        f"- **模型**: `{model_key}` ({model_name})",
        f"- **任务类型**: {task_label}",
        f"- **主指标**: {primary_metric}",
        "",
    ]

    # 预处理信息
    orig = preprocessing_info.get('original_features', '-')
    enc = preprocessing_info.get('encoded_features', '-')
    sel = preprocessing_info.get('selected_features', '-')
    lines.extend([
        "## 预处理流程",
        f"- 原始特征: **{orig}** 列",
        f"- 编码后: **{enc}** 列",
        f"- 特征选择后: **{sel}** 列",
        "",
    ])

    # CV 性能
    if cv_result:
        lines.extend([
            "## 交叉验证性能",
        ])
        for metric, mean in cv_result.mean_scores.items():
            std = cv_result.std_scores.get(metric, 0)
            lines.append(f"- **{metric}**: {mean:.4f} ± {std:.4f}")
        lines.append(f"- **训练耗时**: {cv_result.train_time:.2f}s")
        lines.append("")

    # 超参数
    lines.extend([
        "## 超参数配置",
        "```python",
    ])
    for k, v in sorted(params.items()):
        lines.append(f"{k} = {repr(v)}")
    lines.extend([
        "```",
        "",
    ])

    # 使用建议
    lines.extend([
        "## 使用建议",
        "1. 本脚本使用标准 sklearn / xgboost / lightgbm 等库，可直接在独立环境运行。",
        "2. 预处理链根据原始训练数据的编码策略自动生成，若新数据分布差异较大请重新拟合。",
        "3. 分类任务中标签编码器已保存，预测后可用 `le.inverse_transform(y_pred)` 还原原始标签。",
        "",
    ])

    return "\n".join(lines)


def _generate_code(
    model_key: str,
    task_type: TaskType,
    model_spec: Any,
    params: Dict[str, Any],
    preprocessing_info: Dict[str, Any],
    encoding_report: Optional[List[Dict]] = None,
    feature_selection_report: Optional[List[Dict]] = None,
    df_sample: Optional[Dict] = None,
) -> str:
    """生成可复用的 Python 脚本。"""
    model_name = model_spec.name if model_spec else model_key
    task_label = task_type.value
    is_classification = task_type == TaskType.CLASSIFICATION
    is_regression = task_type == TaskType.REGRESSION
    is_clustering = task_type == TaskType.CLUSTERING

    # 模型导入
    model_import, model_cls_name = _get_model_import(model_spec)

    # 预处理编码策略映射
    cat_cols, num_cols, encoding_strategies = _parse_encoding_report(encoding_report, df_sample)

    # 特征选择
    n_selected = preprocessing_info.get('selected_features', 'all')

    # 参数格式化（处理 tuple 等特殊类型）
    params_lines = _format_params(params)

    # 评估指标
    scoring = _get_scoring(task_type)
    primary_metric = _get_primary_metric(task_type)

    code = textwrap.dedent(f'''\
    """
    Auto-generated training script for {model_name}
    Task: {task_label}
    Generated by Mathematical Modeling
    """

    import pickle
    import pandas as pd
    import numpy as np
    from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, KFold
    from sklearn.pipeline import Pipeline
    from sklearn.compose import ColumnTransformer
    from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder, LabelEncoder
    from sklearn.feature_selection import SelectKBest, f_classif, f_regression, mutual_info_classif, mutual_info_regression
    {model_import}

    # ============================================================
    # 1. 加载数据（请替换为您的数据路径）
    # ============================================================
    # df = pd.read_csv("your_data.csv")
    # X = df.drop(columns=["target"])
    # y = df["target"]

    # 示例：使用随机数据（请删除此部分）
    np.random.seed(42)
    ''')

    # 根据任务类型和数据示例生成示例数据代码
    code += _generate_sample_data_code(task_type, cat_cols, num_cols, df_sample)

    # 预处理部分
    code += textwrap.dedent(f'''

    # ============================================================
    # 2. 预处理配置
    # ============================================================
    # 分类列（根据原始数据自动识别）
    categorical_cols = {cat_cols!r}
    # 数值列
    numerical_cols = {num_cols!r}

    ''')

    # 编码器配置
    code += _generate_preprocessor_code(encoding_strategies, n_selected, is_classification)

    # 标签编码（分类任务）
    if is_classification:
        code += textwrap.dedent('''
    # 标签编码（分类任务）
    le = LabelEncoder()
    y_enc = le.fit_transform(y.astype(str))
    print(f"标签映射: {{dict(zip(le.classes_, le.transform(le.classes_)))}}")

    ''')
    else:
        code += textwrap.dedent('''
    # 回归任务无需标签编码
    y_enc = y

    ''')

    # 数据划分
    code += textwrap.dedent('''
    # ============================================================
    # 3. 数据划分
    # ============================================================
    X_train, X_test, y_train, y_test = train_test_split(
        X, y_enc, test_size=0.2, random_state=42
    )

    ''')

    # 模型初始化
    code += textwrap.dedent(f'''
    # ============================================================
    # 4. 模型初始化
    # ============================================================
    model = {model_cls_name}(
    ''')
    for line in params_lines:
        code += f"        {line},\n"
    code += textwrap.dedent('''    )

    ''')

    # Pipeline
    code += textwrap.dedent('''
    # ============================================================
    # 5. 构建 Pipeline
    # ============================================================
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('selector', selector),
        ('model', model),
    ])

    ''')

    # 训练与评估
    code += textwrap.dedent(f'''
    # ============================================================
    # 6. 训练与交叉验证
    # ============================================================
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42) if y_enc.dtype.kind in 'iub' else KFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(pipeline, X_train, y_train, cv=cv, scoring="{scoring}")
    print(f"CV {primary_metric}: {{cv_scores.mean():.4f}} ± {{cv_scores.std():.4f}}")

    # 全量训练
    pipeline.fit(X_train, y_train)
    test_score = pipeline.score(X_test, y_test)
    print(f"Test score: {{test_score:.4f}}")

    ''')

    # 保存模型
    code += textwrap.dedent('''
    # ============================================================
    # 7. 保存模型与预处理对象
    # ============================================================
    with open("model_pipeline.pkl", "wb") as f:
        pickle.dump(pipeline, f)
    ''')

    if is_classification:
        code += textwrap.dedent('''
    with open("label_encoder.pkl", "wb") as f:
        pickle.dump(le, f)
    ''')

    # 推理示例
    code += textwrap.dedent(f'''

    # ============================================================
    # 8. 推理示例 (predict.py)
    # ============================================================
    ''')
    # 加载并预测
    code += textwrap.dedent('''
    # import pickle
    # with open("model_pipeline.pkl", "rb") as f:
    #     pipeline = pickle.load(f)
    # y_pred = pipeline.predict(X_new)
    ''')

    if is_classification:
        code += textwrap.dedent('''
    # # 还原原始标签
    # with open("label_encoder.pkl", "rb") as f:
    #     le = pickle.load(f)
    # y_pred_labels = le.inverse_transform(y_pred)
    ''')

    code += "\n"
    return code


def _get_model_import(model_spec: Any) -> tuple:
    """获取模型的 import 语句和类名。"""
    if not model_spec or not model_spec.model_class:
        return ("from sklearn.ensemble import RandomForestClassifier", "RandomForestClassifier")
    module = model_spec.model_class.__module__
    name = model_spec.model_class.__name__
    return (f"from {module} import {name}", name)


def _parse_encoding_report(
    encoding_report: Optional[List[Dict]],
    df_sample: Optional[Dict]
) -> tuple:
    """
    解析编码报告，返回分类列、数值列、编码策略映射。
    Fallback：根据 df_sample 推断类型。
    """
    cat_cols = []
    num_cols = []
    strategies = {}

    if encoding_report:
        for row in encoding_report:
            col = row.get('column')
            strategy = row.get('strategy', 'onehot')
            if col:
                cat_cols.append(col)
                strategies[col] = strategy
    elif df_sample:
        # 根据示例数据推断类型
        for col, vals in df_sample.items():
            if col == 'target':
                continue
            sample_vals = vals if isinstance(vals, list) else [vals]
            if any(isinstance(v, str) for v in sample_vals):
                cat_cols.append(col)
                strategies[col] = 'onehot'
            else:
                num_cols.append(col)
    else:
        cat_cols = ["cat_col1", "cat_col2"]  # 占位符
        num_cols = ["num_col1", "num_col2"]

    # 如果没有数值列，给个占位符
    if not num_cols and df_sample:
        for col in df_sample:
            if col != 'target' and col not in cat_cols:
                num_cols.append(col)

    return cat_cols, num_cols, strategies


def _generate_preprocessor_code(
    encoding_strategies: Dict[str, str],
    n_selected: Any,
    is_classification: bool
) -> str:
    """生成预处理 ColumnTransformer 代码。"""
    transformers = []
    onehot_cols = [c for c, s in encoding_strategies.items() if s in ('onehot', 'auto')]
    ordinal_cols = [c for c, s in encoding_strategies.items() if s == 'ordinal']
    label_cols = [c for c, s in encoding_strategies.items() if s == 'label']
    # frequency / target / other -> fallback to ordinal
    other_cols = [c for c, s in encoding_strategies.items() if s not in ('onehot', 'ordinal', 'label', 'auto', 'none')]

    if onehot_cols:
        transformers.append(
            f"        ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False), {onehot_cols!r}),"
        )
    if ordinal_cols:
        transformers.append(
            f"        ('ordinal', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), {ordinal_cols!r}),"
        )
    if label_cols:
        transformers.append(
            f"        ('label', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), {label_cols!r}),"
        )
    if other_cols:
        transformers.append(
            f"        ('other', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), {other_cols!r}),"
        )

    # 数值列总是用 StandardScaler
    transformers.append(
        "        ('num', StandardScaler(), numerical_cols),"
    )

    transformer_block = "\n".join(transformers)

    score_func = "f_classif" if is_classification else "f_regression"
    k = n_selected if isinstance(n_selected, int) and n_selected > 0 else "'all'"

    code = textwrap.dedent(f'''\
    preprocessor = ColumnTransformer(
        transformers=[
    {transformer_block}
        ],
        remainder='drop',
    )

    # 特征选择
    selector = SelectKBest(score_func={score_func}, k={k})

    ''')
    return code


def _generate_sample_data_code(
    task_type: TaskType,
    cat_cols: List[str],
    num_cols: List[str],
    df_sample: Optional[Dict]
) -> str:
    """生成示例数据代码。"""
    n_samples = 100
    code_lines = []

    if df_sample:
        # 基于实际数据示例生成
        for col in cat_cols:
            vals = df_sample.get(col, ['A', 'B', 'C'])
            if isinstance(vals, list):
                code_lines.append(f"    {col!r}: np.random.choice({vals!r}, size={n_samples}),")
            else:
                code_lines.append(f"    {col!r}: np.random.choice(['A', 'B', 'C'], size={n_samples}),")
        for col in num_cols:
            vals = df_sample.get(col, [0.0])
            if isinstance(vals, list) and len(vals) > 0 and isinstance(vals[0], (int, float)):
                mean = sum(vals) / len(vals)
                std = max(1.0, (sum((v - mean) ** 2 for v in vals) / len(vals)) ** 0.5)
                code_lines.append(f"    {col!r}: np.random.normal({mean:.2f}, {std:.2f}, size={n_samples}),")
            else:
                code_lines.append(f"    {col!r}: np.random.randn({n_samples}),")
    else:
        for col in cat_cols:
            code_lines.append(f"    {col!r}: np.random.choice(['A', 'B', 'C'], size={n_samples}),")
        for col in num_cols:
            code_lines.append(f"    {col!r}: np.random.randn({n_samples}),")

    # 目标变量
    if task_type == TaskType.CLASSIFICATION:
        code_lines.append(f"    'target': np.random.choice([0, 1], size={n_samples}),")
    elif task_type == TaskType.REGRESSION:
        code_lines.append(f"    'target': np.random.randn({n_samples}),")
    else:
        code_lines.append(f"    'target': np.random.choice([0, 1, 2], size={n_samples}),")

    data_block = "\n".join(code_lines)
    return textwrap.dedent(f'''\
    df = pd.DataFrame({{
    {data_block}
    }})
    X = df.drop(columns=["target"])
    y = df["target"]

    ''')


def _format_params(params: Dict[str, Any]) -> List[str]:
    """格式化参数字典为 Python 代码行。"""
    lines = []
    for k, v in sorted(params.items()):
        if isinstance(v, str):
            lines.append(f"{k}={v!r}")
        elif isinstance(v, (list, tuple)):
            lines.append(f"{k}={v!r}")
        elif isinstance(v, bool):
            lines.append(f"{k}={str(v)}")
        elif v is None:
            lines.append(f"{k}=None")
        elif isinstance(v, (int, float)):
            lines.append(f"{k}={v}")
        else:
            lines.append(f"{k}={v!r}")
    return lines


def _get_primary_metric(task_type: TaskType) -> str:
    """获取主指标名称。"""
    if task_type.value == 'classification':
        return 'accuracy'
    elif task_type.value == 'regression':
        return 'r2'
    else:
        return 'silhouette'


def _get_scoring(task_type: TaskType) -> str:
    """获取 sklearn scoring 名称。"""
    if task_type.value == 'classification':
        return 'accuracy'
    elif task_type.value == 'regression':
        return 'r2'
    else:
        return 'silhouette'
