"""Prospective logical optimization and relational-semantics combinations."""
from __future__ import annotations
from .automated_benchmark import AutomatedBenchmarkCase
def t(name,rows):return {"name":name,"format":"records","rows":rows}
def build_logic_temporal_holdout(*,seed:int=20260927):
 if type(seed)is not int or not 0<=seed<=2**32-1:raise ValueError("holdout_seed_invalid")
 common={"family":"modeling_optimization","structure":"logical_resource_allocation_milp","objective_unit":"currency","direction":"maximize","integer_indices":[0,1,2,3],"tolerance":1e-8}
 c1=AutomatedBenchmarkCase("logic-fixed-cardinality","modeling_optimization","最多启用 1 种产品，生产整数批次并扣除固定启动成本，在工时内最大化净利润。",{"attachments":[t("items",[{"item":"A","profit":6.,"fixed_cost":2.,"labor":2.},{"item":"B","profit":5.,"fixed_cost":1.,"labor":1.}]),t("limits",[{"resource":"labor","capacity":6.}])],"integer_decisions":True},{**common,"decision_variables":["A_qty","B_qty","A_open","B_open"],"constraint_ids":["labor","link:A","link:B","maximum_active_items"],"decision_units":{"A_qty":"item","B_qty":"item","A_open":"binary","B_open":"binary"},"objective":29.,"objective_coefficients":[6,5,-2,-1],"bounds":[[0,3],[0,6],[0,1],[0,1]],"A_ub":[[2,1,0,0],[1,0,-3,0],[0,1,0,-6],[0,0,1,1]],"b_ub":[6,0,0,1],"known_solution":[0,6,0,1]},"logic-fixed-cardinality","internal-logic-temporal-v8")
 c2=AutomatedBenchmarkCase("logic-lot-exclusive","modeling_optimization","同一互斥组最多启用一个方案；满足各自最小批量并在容量内最大化利润。",{"attachments":[t("items",[{"item":"A","profit":6.,"minimum_lot":2.,"activation_group":"G","labor":1.},{"item":"B","profit":7.,"minimum_lot":3.,"activation_group":"G","labor":1.}]),t("limits",[{"resource":"labor","capacity":5.}])],"integer_decisions":True},{**common,"decision_variables":["A_qty","B_qty","A_open","B_open"],"constraint_ids":["labor","link:A","minimum_lot:A","link:B","minimum_lot:B","exclusive_group:G"],"decision_units":{"A_qty":"item","B_qty":"item","A_open":"binary","B_open":"binary"},"objective":35.,"objective_coefficients":[6,7,0,0],"bounds":[[0,5],[0,5],[0,1],[0,1]],"A_ub":[[1,1,0,0],[1,0,-5,0],[-1,0,2,0],[0,1,0,-5],[0,-1,0,3],[0,0,1,1]],"b_ub":[5,0,0,0,0,1],"known_solution":[0,5,0,1]},"logic-lot-exclusive","internal-logic-temporal-v8")
 c3=AutomatedBenchmarkCase("relation-weighted-bridge","modeling_multi_table","按桥表份额将账单金额分配到类别并汇总。",{"attachments":[t("bills",[{"bill":"B1","amount":12.},{"bill":"B2","amount":8.}]),t("shares",[{"bill":"B1","category":"C1","share":.4},{"bill":"B1","category":"C2","share":.6},{"bill":"B2","category":"C1","share":1.}]),t("categories",[{"category":"C1","group":"X"},{"category":"C2","group":"Y"}])]},{"family":"modeling_multi_table","structure":"weighted_bridge_group_sum","join_keys":["bill","category"],"aggregation":"weighted_sum","point_in_time":False,"rows":3,"group_totals":{"X":12.8,"Y":7.2},"tolerance":1e-8},"relation-weighted-bridge","internal-logic-temporal-v8")
 c4=AutomatedBenchmarkCase("relation-validity-interval","modeling_multi_table","仅按事件落入的有效起止区间关联分组并汇总。",{"attachments":[t("events",[{"entity":"E1","event_time":"2026-01-10","amount":3.},{"entity":"E1","event_time":"2026-02-10","amount":5.},{"entity":"E2","event_time":"2026-01-20","amount":7.}]),t("history",[{"entity":"E1","effective_from":"2026-01-01","effective_to":"2026-02-01","segment":"A"},{"entity":"E1","effective_from":"2026-02-01","effective_to":"2026-03-01","segment":"B"},{"entity":"E2","effective_from":"2026-01-01","effective_to":"2026-02-01","segment":"A"}])]},{"family":"modeling_multi_table","structure":"validity_interval_group_sum","join_keys":["entity"],"aggregation":"sum","point_in_time":True,"rows":3,"group_totals":{"A":10.,"B":5.},"tolerance":1e-8},"relation-validity-interval","internal-logic-temporal-v8")
 result=(c1,c2,c3,c4)
 for c in result:c.validate()
 return result
__all__=["build_logic_temporal_holdout"]
